# FROM python
FROM python:3.11.2-slim-bullseye

USER root

RUN apt update && apt upgrade -y

COPY . /myapp

WORKDIR /myapp

RUN pip3 install -r requirements.txt

EXPOSE 8000

ENTRYPOINT ["python3"]
CMD ["manage.py", "runserver", "0.0.0.0:8000"]