export interface Iflight{
    id:number
    flightNum:string
    type:string
    stdLocal:string
    etdLocal:string
    dest:string
    aircraftType:string
    aircraftReg:string
    gate:string
    pit:string
    agents?:number[]
    ramp?:number[]
    wingWalker?:number[]
    ambulift:boolean
    obTime:string
    delaycode:string[]
    delaytime:string[]
    arivalAgent:number
    clc:number
    pushback:number
    sorter:number
    spv:number
}