# Generated by Django 4.1.7 on 2023-03-19 08:02

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmploeeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phoneNum', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=500)),
                ('birthDate', models.DateField(null=True)),
                ('needTaxi', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='holder.jpeg', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flightNum', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=20)),
                ('stdLocal', models.DateTimeField()),
                ('etdLocal', models.DateTimeField(null=True)),
                ('dest', models.CharField(max_length=255)),
                ('aircraftType', models.CharField(max_length=10)),
                ('aircraftReg', models.CharField(max_length=15)),
                ('gate', models.CharField(max_length=3)),
                ('pit', models.CharField(max_length=10)),
                ('agents', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None)),
                ('ramp', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None)),
                ('wingWalker', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None)),
                ('ambulift', models.BooleanField(null=True)),
                ('obTime', models.DateTimeField(null=True)),
                ('delaycode', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5, null=True), null=True, size=None)),
                ('delaytime', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(null=True), null=True, size=None)),
                ('arivalAgent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_agent_flights', to=settings.AUTH_USER_MODEL)),
                ('clc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clc_flights', to=settings.AUTH_USER_MODEL)),
                ('pushback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pushback_flights', to=settings.AUTH_USER_MODEL)),
                ('sorter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sorting_flights', to=settings.AUTH_USER_MODEL)),
                ('spv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_flights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.departments'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.roles'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='base.emploeetype'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
