FROM selenium/standalone-chrome:110.0-chromedriver-110.0

USER root
RUN sudo apt update && sudo apt upgrade -y
RUN sudo apt install xfce4 xfce4-goodies -y
RUN sudo apt install tightvncserver -y

EXPOSE 4444
